[package]
name = "usb-bridge-client"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
clap = { version = "4", features = ["derive", "env"] }
usb-bridge-client-core = { path = "core" }
usb-bridge-protocol = { path = "../crates/protocol" }
